/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/





/******************************************************************************
 * \file Cpu0_Main.c
 * \brief ASCLIN1 RX @ P14.8 (Nichia / Osram dual-device) + FPS via STM0
 ******************************************************************************/

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"

#include "asclin1_dma.h"
#include "can_diag.h"
#include "can_hw.h"
#include "can_uart_bridge.h"
#include "can_uart_master.h"
#include "rxmon.h"
#include "osram_frame.h"
#include "frame_eth.h"
#include "device_mode.h"
#include "adapter_ctrl.h"
#include "lvds_fault_inject.h"
#include "lvds_tx.h"
#include "avtp_rx.h"
#include "direct_mode.h"

/* STM timing */
#include "Stm/Std/IfxStm.h"
#include <string.h>

/* Basler video camera */
#include "camera_trigger.h"

/* -------------------- CPU sync -------------------- */
IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

/* 64-bit STM from 32-bit TIM0 with wrap extension */
static uint32 stm_lo_prev = 0;
static uint64 stm_hi_acc  = 0;

/* IFX_INLINE already expands to static inline in iLLD; don't add another 'static' */
IFX_INLINE uint64 stm_now64(void)
{
    uint32 lo = IfxStm_getLower(&MODULE_STM0); /* TIM0.U (32-bit) */
    if (lo < stm_lo_prev)                      /* wrap detected    */
    {
        stm_hi_acc += (1ULL << 32);
    }
    stm_lo_prev = lo;
    return (stm_hi_acc | (uint64)lo);
}

/* Accurate FPS window (1 second) */
static uint64 fps_t0 = 0;
static uint64 fps_win = 0;
static uint32 framesOk_base = 0;

/* Standalone recovery: if an unplug/reset/power transient wedges the
 * ASCLIN1/DMA LVDS path, re-arm only the LVDS receiver and parser. */
#define LVDS_RECOVERY_TIMEOUT_MS    1000u
#define LVDS_RECOVERY_COOLDOWN_MS   1000u
/* Main-loop fairness: drain at most N completed LVDS DMA buffers per pass so
 * command RX/TX and bridge out-drain are serviced regularly on long runtimes. */
#define LVDS_DRAIN_BUDGET           4u

volatile uint32 g_lvdsRecoveryCount;
volatile uint32 g_lvdsRecoveryLastDevice;
volatile uint32 g_lvdsRecoveryLastProgress;

static uint64 s_lvdsRecoveryTimeoutTicks;
static uint64 s_lvdsRecoveryCooldownTicks;
static uint64 s_lvdsLastProgressTick;
static uint64 s_lvdsLastRecoveryTick;
static uint32 s_lvdsLastProgress;
static FrameEthDevice s_lvdsLastDevice = FE_DEVICE_NICHIA;
static boolean s_cameraTriggerFallback;


static void fps_init(void)
{
    fps_t0  = stm_now64();
    /* API returns sint32; cast to u64 */
    fps_win = (uint64)IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 1000);
    framesOk_base = 0;
}

static void fps_update(void)
{
    uint64 now = stm_now64();
    if ((now - fps_t0) >= fps_win)
    {
        g_rxmon.framesPerSecond  = g_rxmon.framesOk - framesOk_base;   /* lines per second */
        g_rxmon.lastSecondFrames = g_rxmon.framesOk;
        framesOk_base            = g_rxmon.framesOk;
        fps_t0                   = now;
    }
}

static uint32 lvds_progress_counter(FrameEthDevice device)
{
    return (device == FE_DEVICE_OSRAM)
        ? g_feStats.osramFramesPushed
        : g_feStats.nichiaFramesAssembled;
}

static void lvds_recovery_init(void)
{
    s_lvdsRecoveryTimeoutTicks =
        (uint64)IfxStm_getTicksFromMilliseconds(&MODULE_STM0, LVDS_RECOVERY_TIMEOUT_MS);
    s_lvdsRecoveryCooldownTicks =
        (uint64)IfxStm_getTicksFromMilliseconds(&MODULE_STM0, LVDS_RECOVERY_COOLDOWN_MS);

    s_lvdsLastDevice       = device_mode_get();
    s_lvdsLastProgress     = lvds_progress_counter(s_lvdsLastDevice);
    s_lvdsLastProgressTick = stm_now64();
    s_lvdsLastRecoveryTick = 0u;
    s_cameraTriggerFallback = FALSE;
}

static void lvds_recover_rx_path(FrameEthDevice device)
{
    g_asclin1_dma.pCompletedBuffer = NULL_PTR;

    if (device == FE_DEVICE_OSRAM)
    {
        osram_frame_init();
        asclin1_dma_init(DM_OSRAM_BAUD, Frame_8Odd1);
    }
    else
    {
        rxmon_reset();
        asclin1_dma_init(DM_NICHIA_BAUD, Frame_8N1);
    }

    frame_eth_reset_frame_state();

    g_lvdsRecoveryCount++;
    g_lvdsRecoveryLastDevice = (uint32)device;
    g_lvdsRecoveryLastProgress = s_lvdsLastProgress;
}

static void lvds_recovery_tick(void)
{
    FrameEthDevice device = device_mode_get();
    uint32 progress = lvds_progress_counter(device);
    uint64 now = stm_now64();

    /* In Direct Control Mode the AURIX is the LVDS source and ASCLIN1 is
     * configured for transmit, so there is no receive path to recover. */
    if (lvds_tx_is_enabled())
        return;

    if (device != s_lvdsLastDevice)
    {
        s_lvdsLastDevice       = device;
        s_lvdsLastProgress     = progress;
        s_lvdsLastProgressTick = now;
        s_lvdsLastRecoveryTick = 0u;
        if (s_cameraTriggerFallback)
        {
            camera_trigger_set_mode(CAM_TRIG_SYNC);
            camera_trigger_start();
            s_cameraTriggerFallback = FALSE;
        }
        return;
    }

    if (progress != s_lvdsLastProgress)
    {
        s_lvdsLastProgress     = progress;
        s_lvdsLastProgressTick = now;
        if (s_cameraTriggerFallback)
        {
            /* Resume frame-synchronised acquisition as soon as LVDS returns. */
            camera_trigger_set_mode(CAM_TRIG_SYNC);
            camera_trigger_start();
            s_cameraTriggerFallback = FALSE;
        }
        return;
    }

    if ((now - s_lvdsLastProgressTick) < s_lvdsRecoveryTimeoutTicks)
        return;

    if (!s_cameraTriggerFallback)
    {
        /* No LVDS frame for the watchdog interval: keep the camera alive at
         * the configured 50 fps trigger rate until LVDS resumes. */
        camera_trigger_set_mode(CAM_TRIG_FREERUN);
        camera_trigger_start();
        s_cameraTriggerFallback = TRUE;
    }

    if ((s_lvdsLastRecoveryTick != 0u) &&
        ((now - s_lvdsLastRecoveryTick) < s_lvdsRecoveryCooldownTicks))
        return;

    s_lvdsLastRecoveryTick = now;
    lvds_recover_rx_path(device);
    s_lvdsLastProgress     = lvds_progress_counter(device);
    s_lvdsLastProgressTick = now;
}

/* User callback: feed appropriate parser based on device mode */
static void consume_dma_buffer(const uint8 *data, uint32 len)
{
    if (device_mode_get() == FE_DEVICE_OSRAM)
        osram_frame_feed(data, len);
    else
        rxmon_feed(data, len);
}

void core0_main(void)
{
    /* Disable watchdogs for debugging (enable & service in production) */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    IfxCpu_enableInterrupts();

    /* ── Device mode selection ──
     * Change to FE_DEVICE_NICHIA for Nichia (12.5 Mbaud, 8O1, 256×64).
     * Change to FE_DEVICE_OSRAM for Osram (20 Mbaud, 8O1, 320×80).
     * This configures ASCLIN1 (LVDS), parsers, the CAN-UART bridge and
     * GETH all in one call.
     */
    device_mode_init(FE_DEVICE_OSRAM);

    /* Disable CAN-UART monitor TX at boot  */
    g_diagSniffEnabled = 0u;

    /* SmartVisio Adapter: configure all GPIO selectors.
     * Current default after reset/run = ECU control mode + ECU↔LSM
     * routing (CAN_SEL Low), so CAN traffic goes through SmartVisio adapter directly
     * from the ECU to the LSM and vice versa. */
    adapter_ctrl_init();

    /* Direct Control Mode LVDS generator (ASCLIN1 TX on P02.2).
     * Stays disarmed until a SET_ADAPTER_MODE command selects Direct control. */
    lvds_tx_init();
    avtp_rx_init();
    direct_mode_init();
    can_uart_master_init();

    /* Boot default: forwarding bridge inactive so Direct ECU↔LSM
     * has CAN-UART communication without waiting for a UI command.*/
    can_uart_bridge_set_active(FALSE);

    /* Basler trigger on P02.3 -> camera Pin 3 (Line3), GND -> Pin 6 */
    camera_trigger_init();
    /* SYNC mode: trigger fires on each LVDS frame-complete (from osram_frame.c).
     * Pulse width 200µs is enough for the camera to detect rising edge.
     * Camera should be in Timed mode with ExposureTimeRaw = 16100 µs
     * (= one full Osram LED scan cycle, eliminates checkerboard flicker). */
    camera_trigger_set_period_us(20000U, 200U);
    camera_trigger_set_mode(CAM_TRIG_SYNC);
    camera_trigger_start();

    /* FPS */
    fps_init();
    lvds_recovery_init();

    while (1)
    {
        /* CPU0 owns ASCLIN1, DMA, GETH and the frame parsers.  A TFT touch
         * request is only a mailbox notification; apply it here so no other
         * core reconfigures these peripherals concurrently with this loop. */
        device_mode_process_request();

        /* Poll for incoming command packets (device mode switch from PC).
         * Must run every iteration to drain all RX buffers and prevent
         * DMA descriptor ring exhaustion. */
        frame_eth_poll_rx();
        adapter_ctrl_tick();
        lvds_fault_tick();
        direct_mode_tick();
        lvds_tx_tick();

        /* Drain ALL completed DMA buffers before sending Ethernet.
         * This prevents data loss when frame_eth_send_pending() takes
         * longer than the DMA buffer fill time (~1.28 ms at 20 Mbaud). */
        {
            uint8 *completed;
            uint8 drainCount = 0u;
            while (drainCount < LVDS_DRAIN_BUDGET &&
                   (completed = asclin1_dma_get_completed_buffer()) != NULL_PTR)
            {
                consume_dma_buffer(completed, ASCLIN1_DMA_BUFFER_SIZE);
                drainCount++;
            }
        }

        asclin1_dma_poll_health();
        if (device_mode_get() == FE_DEVICE_NICHIA)
        {
            g_rxmon.hwFrameErr   = g_asclin1_dma.frameErrors;
            g_rxmon.hwParityErr  = g_asclin1_dma.parityErrors;
            g_rxmon.hwOverrunErr = g_asclin1_dma.overrunErrors;
        }

        lvds_recovery_tick();

        /* Adapter_V2 active CAN-UART bridge: the byte forwarding and monitor-
         * frame extraction now run on CPU2 (off the real-time LVDS path).  Here
         * on CPU0 we only drain the completed monitor frames handed over through
         * the cross-core ring into the (single-core) can_diag queue, which is
         * then sent to the PC by frame_eth_send_can_diag_pending() below. */
        can_uart_bridge_poll_out();
        can_uart_master_poll_out();

        /* Send assembled frame over Ethernet (if ready) */
        frame_eth_send_pending();
        if (g_diagSniffEnabled)
            frame_eth_send_can_diag_pending();

        /* Update FPS once per second */
        fps_update();
    }
}

