/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/





/******************************************************************************
 * \file Cpu0_Main.c
 * \brief ASCLIN9 RX @ P14.7 (Nichia 12.5 Mbps) + FPS via STM0
 ******************************************************************************/

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"

#include "asclin9_dma.h"
#include "rxmon.h"
#include "nichia_eth.h"

/* STM timing */
#include "Stm/Std/IfxStm.h"

/* -------------------- CPU sync -------------------- */
IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

/* 64-bit STM from 32-bit TIM0 with wrap extension */
static uint32 stm_lo_prev = 0;
static uint64 stm_hi_acc  = 0;

/* IFX_INLINE already expands to static inline in iLLD; don't add another 'static' */
IFX_INLINE uint64 stm_now64(void)
{
    uint32 lo = IfxStm_getLower(&MODULE_STM0); /* TIM0.U (32-bit) */
    if (lo < stm_lo_prev)                      /* wrap detected    */
    {
        stm_hi_acc += (1ULL << 32);
    }
    stm_lo_prev = lo;
    return (stm_hi_acc | (uint64)lo);
}

/* Accurate FPS window (1 second) */
static uint64 fps_t0 = 0;
static uint64 fps_win = 0;
static uint32 framesOk_base = 0;

static void fps_init(void)
{
    fps_t0  = stm_now64();
    /* API returns sint32; cast to u64 */
    fps_win = (uint64)IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 1000);
    framesOk_base = 0;
}

static void fps_update(void)
{
    uint64 now = stm_now64();
    if ((now - fps_t0) >= fps_win)
    {
        g_rxmon.framesPerSecond  = g_rxmon.framesOk - framesOk_base;   /* lines per second */
        g_rxmon.lastSecondFrames = g_rxmon.framesOk;
        framesOk_base            = g_rxmon.framesOk;
        fps_t0                   = now;
    }
}

/* User callback: feed rxmon parser (called from main loop) */
static void consume_dma_buffer(const uint8 *data, uint32 len)
{
    rxmon_feed(data, len);
}

void core0_main(void)
{
    /* Disable watchdogs for debugging (enable & service in production) */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    IfxCpu_enableInterrupts();

    /* Start ASCLIN9 @ 12.5 Mbaud with DMA + dual buffer */
    asclin9_dma_init(12500000u, Frame_8N1);

    /* Initialise GETH for Nichia frame Ethernet TX */
    nichia_eth_init();

    /* FPS */
    fps_init();

    while (1)
    {
        /* Check if DMA has filled a buffer */
        uint8 *completed = asclin9_dma_get_completed_buffer();
        if (completed != NULL_PTR)
        {
            /* Feed the parser (non-blocking copy) */
            consume_dma_buffer(completed, ASCLIN9_DMA_BUFFER_SIZE);
        }

        /* Send assembled Nichia frame over Ethernet (if ready) */
        nichia_eth_send_pending();

        /* Update FPS once per second */
        fps_update();
    }
}

